name: NBTEdit
version: ${project.version}
main: retrixastudios.nbtedit.NBTEdit
api-version: 1.16
authors: [Retrixa]
description: Command based NBT editor.
commands:
  nbtplayer:
    usage: /<command>
    aliases: [nbtp]
    description: NBTEdit player parent command.
  nbtitem:
    usage: /<command>
    aliases: [nbti]
    description: NBTEdit item parent command.
